create table carro (
        id bigint generated by default as identity,
        descricao varchar(255),
        latitude varchar(255),
        longitude varchar(255),
        nome varchar(255),
        tipo varchar(255),
        url_foto varchar(255),
        url_video varchar(255),
        primary key (id)
    );
